version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8082"