db:
  username: ${user.name:postgres}
  password: 12345
  driver: PostgresDriver
  url: 5432:postgres
  hosts: localhost, 127.0.0.1
  properties:
    first: 123
    second: 345
    another.value: Third
  pool:
      size: 12
      timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: WARN
    com.dmdev.spring.database.pool.ConnectionPool: INFO
  file:
    name: dmdev.log
    path: /

spring:
  profiles:
    active: qa